### PR TITLE
widgets/recent_files: fix on utf8 hosts with umlauts

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by sttts** [comment]
Wondering in which setup is qtpyvcp tested? I noticed in a couple of places that it does not handle utf8 chars correctly. Probably it's due to python2. How is python3 support going? Python2 is gone in recent distros.

**Comment by TurBoss** [comment]
Hello, my dev environment is a linuxcnc 2.80 iso so debian 10 spanish locale

There are others that run linux mint but all debian distributions 

About python 3 I think we should upgrade when linuxcnc debs with python 3 support are available.

There is a python3 branch in qtpyvcp but never went master, and the only way to get linuxcnc with python 3 support is build from sources iirc

**Comment by sttts** [comment]
I tried to run via `linuxcnc config/probe_basic/probe_basic.ini` and I did not get this error. Wondering whether it is anything with my ini.

**Comment by sttts** [comment]
Seems to work fine. Not sure what was different last time.

**Pull request closed without merging**
